# Generated by Django 4.0.4 on 2022-05-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=20)),
                ('financiacion', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=50)),
                ('universidad', models.CharField(max_length=100)),
                ('requerimientos', models.CharField(max_length=500)),
            ],
        ),
    ]
